### ISSUE TITLE
New field TB  Screening  this needs to be aligned to existing tests. Add section to app and must align with how other tests are implemented i.e done earlier, ordered etc but options on reason for not done should be as provided in the data 

### ISSUE THREAD

**Issue by gladysyabs** [BlueCodeSystems/who-anc#130]
**Reasons  as provided in the data dictionary**
Reason TB screening not done

- Sputum smear not available
- Sputum culture not available
- GeneXpert machine not available
- X-ray machine not available
- No sputum supplies available
- Machine not functioning
- Technician not available

**Comment by tobiasmakai** [comment]
This was not correctly implemented.
