### ISSUE TITLE
Contact Date: What is the essence of the calculated period in the brackets?

### ISSUE THREAD

**Issue by tobiasmakai** [BlueCodeSystems/who-anc#135]
![Screenshot_20211104-124639_WHO ANC](https://user-images.githubusercontent.com/25362528/140301334-2c279f74-6f01-4ef5-bfa8-9def15a59821.jpg)

**Comment by MwambaK** [comment]
It has been placed on to show how long ago the contact was made.

**Comment by tobiasmakai** [comment]
I don't it is necessary considering the app already shows when the next contact is due.

**Comment by MwambaK** [comment]
noted, should i remove it?

**Comment by tobiasmakai** [comment]
Yes.

**Comment by MwambaK** [comment]
okay noted
