### ISSUE TITLE
On ultrasound scan - Fetal heartbeat Present (Yes or No) - Fetal Heart rate (if fetal heartbeat is yes)  then Gestation age   and then  Fetal weight in grams

### ISSUE THREAD

**Issue by gladysyabs** [BlueCodeSystems/who-anc#209]
Gestation age don't enter anything but this will relay on the first body weight (base weight) to the subsequent contacts
Fetal weight will keep on changing - in grams

**Comment by tobiasmakai** [comment]
Based on user feedback, the "Fetal weight" field should show even if the fetal heart rate is not provided. Closing this and opening a new one.
