### ISSUE TITLE
On the Blood Pressure  the field systolic, the normal upper reading should be  from 90 - 139 and Diastolic  lower reading 60 – 89

### ISSUE THREAD

**Issue by gladysyabs** [BlueCodeSystems/who-anc#270]

**Comment by tobiasmakai** [comment]
@MwambaK 
Ensure the Blood Pressure works as follows;
- [ ] The normal range for the “Systolic blood pressure” should be 90 - 139.
- [ ] The normal range for the “Diastolic blood pressure” should be 60 – 89.
- [ ] Repeat fields should be activated for anything outside the range for both blood pressure fields.
- [ ] An alert flag with the message “Repeat the BP immediately” should appear whenever the reading entered is below the normal range for either the Systolic or Diastolic blood pressure.
- [ ] For BP entries above the normal range for both the Systolic and Diastolic blood pressure, the application should flag an alert with the message “Repeat after 10 – 15 minutes, use a different machine if available.” 
- [ ] Low Diastolic blood pressure (below the lower limit - 60) should trigger an alert or information tip with the message “Fluid resuscitation (normal saline or ringer solution)”.
- [ ] The information tip (alert/popup) for management of High BP should be enhanced to include the phrase “Give magnesium sulfate 14g (Dilute 8ml to 10ml…...” (full message to be provided later)
- [ ] Systolic blood pressure should always be higher than Diastolic blood pressure. Entries to the contrary should flag an appropriate error.

**Comment by gladysyabs** [comment]
This issue has is not bringing the repeat fields even after entering something that is outside the range

**Comment by tobiasmakai** [comment]
@MwambaK ensure correct validations and alerts as per the comment above.
![Screenshot_20220118-002744_WHO ANC](https://user-images.githubusercontent.com/25362528/149843813-1806c76d-a546-4326-96a6-b918b1a107cb.jpg)

**Comment by tobiasmakai** [comment]
To be tested further.
