### ISSUE TITLE
Rearrangement of the fields on physical exam according to the ANC card.

### ISSUE THREAD

**Issue by gladysyabs** [BlueCodeSystems/who-anc#343]
The field Symphysis-fundal height (SFH) in centimeters (cm) should be active if EGA is equal or greater than 22 weeks. The field Height of fundus should be active if EGA is less than 22 weeks.
[ ] Symphysis-fundal height (SFH) in centimeters (cm)
[ ] Height of fundus
[ ] Fetal lie - This field should have the options "Longitudinal, Transverse, Oblique".
[ ] Fetal presentation - This field should have the options "Breech, Cephalic, Other".
[ ] Descent - This field should have the options "5/5; 4/5; 3/5; 2/5; 1/5 and 0/5".
[ ] Fetal Heart -This field should have the options "Present, Absent". If present show fetal heart rate (bmp). If absent show alert "No fetal heartbeat felt. Refer to hospital"
[ ] Fetal heart rate (bmp)
[ ] Fetal weight (grams)
[ ] No. of fetuses
[ ] No. of fetuses unknown

Then re-arrange the sections to start wit Fetal Assessment then Blood pressure then Height & Weight then Maternal Exam should be the last section.
So that it is similar to how the information flows on the ANC card.

**Comment by tobiasmakai** [comment]
Based on feedback this will have to change. Closing the issue as it is now overridden by issue #464
