### ISSUE TITLE
Add validation rules to the phone number fields

### ISSUE THREAD

**Issue by tobiasmakai** [BlueCodeSystems/who-anc#45]
![Screenshot_20211012-133415_WHO ANC](https://user-images.githubusercontent.com/25362528/136949158-10064dd2-dd6e-4cc4-ae98-b1a631e5ff35.jpg)

**Comment by gladysyabs** [comment]
Allow this field to only accept numbers starting with 096,097,095,076 and 077. You can refer this to ECAP
